[build]
  command = "flutter build web --release"
  publish = "build/web"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/shwary/*"
  to = "/.netlify/functions/shwary/:splat"
  status = 200
  force = true
